export const hrvatski = {
  id: 'hr',
  jezik: 'Hrvatski',
  otajstvoSvjetla: 'Svijetlo',
  otajstvoZalosno: 'Žalosno',
  otajstvoSlavno: 'Slavno',
  otajstvoRadosna: 'Radosna',
  amen: 'Amen.',
  naslov0: 'Početak krunice - †',
  text0a: 'U ime Oca i Sina † i Duha Svetoga.',
  naslov1: '1. zrnce',
  text1: 'U ime Oca i Sina † i Duha Svetoga.',
  naslov2: '2. zrnce',
  text2: 'U ime Oca i Sina † i Duha Svetoga.',
};
