export const talijanski = {
  id: 'it',
  jezik: 'Talijanski',
  daniTjedan: [
    { value: 'pon', label: 'xxMonday ' },
    { value: 'uto', label: 'xxTuesday' },
    { value: 'sri', label: 'xxWednesday ' },
    { value: 'cet', label: 'xxThursday' },
    { value: 'pet', label: 'xxFriday' },
    { value: 'sub', label: 'xxSaturday' },
    { value: 'ned', label: 'xxSunday' },
  ],
  title: 'Molitva gospine krunice',
  otajstvoSvjetla: 'Svjetla Taljano',
  otajstvoZalosno: 'Zalosno Taljano ',
  otajstvoSlavno: 'Slavno Taljano ',
  otajstvoRadosna: ' Radosna Taljano ',
  uImeOcaSina: 'U ime Oca i Sina † i Duha Svetoga.',
  oceNas: 'Oče naš',
  isuse: 'Isuse',
  oceNasText:
    ', koji jesi na nebesima, sveti se ime tvoje. Dođi kraljevstvo tvoje. Budi volja tvoja, kako na nebu tako i na zemlji. Kruh naš svagdanji daj nam danas, i otpusti nam duge naše, kako i mi otpuštamo dužnicima našim, i ne uvedi nas u napast, nego izbavi nas od zla.',
  amen: 'Amen.',
  slavaOcu:
    'Slava Ocu i Sinu † i Duhu Svetomu. Kako bijaše na početku, tako i sada i vazda i u vijeke vjekova.',
  zdravoMarijaPocetak:
    'Zdravo Marijo, milosti puna, Gospodin s tobom. Blagoslovljena ti među ženama i blagoslovljen plod utrobe tvoje,',
  zdravoMarijaKraj:
    'Sveta Marijo, Majko Božja, moli za nas grješnike, sada i na času smrti naše.',
  oMojIsuse:
    'O moj Isuse, oprosti nam naše grijehe, očuvaj nas od paklenog ognja, dovedi u raj sve duše, osobito one, kojima je najpotrebnije tvoje milosrđe.',
  zdravoKraljice:
    'Zdravo Kraljice, Majko milosrđa, živote, slasti i ufanje naše, zdravo!\n K tebi vapijemo prognani sinovi Evini. \n K tebi uzdišemo tugujući i plačući u ovoj suznoj dolini. \n Svrni, dakle, Zagovornice naša one svoje milostive oči na nas te nam poslije ovoga progonstva pokaži Isusa, blagoslovljeni plod utrobe svoje. \n O blaga, o mila, o slatka Djevice Marijo.',
  text0a: 'U ime Oca i Sina † i Duha Svetoga.',
  text0b:
    ', to je tebi za ljubav, za obraćenje grješnika i kao naknada za uvrede koje se nanose Bezgrešnom Srcu Marijinu.',
  text0c: 'APOSTOLSKO VJEROVANJE',
  text0d:
    'Vjerujem u Boga, Oca svemogućega, Stvoritelja neba i zemlje. I u Isusa Krista, Sina njegova jedinoga, Gospodina našega, koji je začet po Duhu Svetom, rođen od Marije Djevice, mučen pod Poncijem Pilatom, raspet, umro i pokopan; sašao nad pakao; treći dan uskrsnuo od mrtvih; uzašao na nebesa, sjedi o desnu Boga Oca svemogućega; odonud će doći suditi žive i mrtve. Vjerujem u Duha Svetoga, svetu Crkvu katoličku, općinstvo svetih, oproštenje grijeha, uskrsnuće tijela, i život vječni.',
  text1: 'U ime Oca i Sina † i Duha Svetoga.',
  text2: 'Isus, koji neka nam umnoži vjeru!',
  text3: 'Isus, koji neka nam učvrsti ufanje!',
  text4: 'Isus, koji neka nam usavrši ljubav!',
  naslov0: 'Talijano  krunice - †',
  naslov1: '1. Talijeno zrno Talijansko zrce',
  naslov2: '2. Talijansko zrce',
  naslov3: '3. Talijansko zrce',
  naslov4: '4. Talijansko zrce',
  naslov5: '5. Talijansko zrce',
  naslov6: 'Medaljica Krunice',
  naslov7: '1. Talijansko zrce prve desetice',
  naslov8: '2. Talijansko zrce prve desetice',
  naslov9: '3. Talijansko zrce prve desetice',
  naslov10: '4. Talijansko zrce prve desetice',
  naslov11: '5. Talijansko zrce prve desetice',
  naslov12: '6. Talijansko zrce prve desetice',
  naslov13: '7. Talijansko zrce prve desetice',
  naslov14: '8. Talijansko zrce prve desetice',
  naslov15: '9. Talijansko zrce prve desetice',
  naslov16: '10. Talijansko zrce prve desetice',
  naslov17: 'Druga desetica',
  naslov18: '1. Talijansko zrce druge desetice',
  naslov19: '2. Talijansko zrce druge desetice',
  naslov20: '3. Talijansko zrce druge desetice',
  naslov21: '4. Talijansko zrce druge desetice',
  naslov22: '5. Talijansko zrce druge desetice',
  naslov23: '6. Talijansko zrce druge desetice',
  naslov24: '7. Talijansko zrce druge desetice',
  naslov25: '8. Talijansko zrce druge desetice',
  naslov26: '9. Talijansko zrce druge desetice',
  naslov27: '10. Talijansko zrce druge desetice',
  naslov28: 'Treća desetica',
  naslov29: '1. Talijansko zrce treće desetice',
  naslov30: '2. Talijansko zrce treće desetice',
  naslov31: '3. Talijansko zrce treće desetice',
  naslov32: '4. Talijansko zrce treće desetice',
  naslov33: '5. Talijansko zrce treće desetice',
  naslov34: '6. Talijansko zrce treće desetice',
  naslov35: '7. Talijansko zrce treće desetice',
  naslov36: '8. Talijansko zrce treće desetice',
  naslov37: '9. Talijansko zrce treće desetice',
  naslov38: '10. Talijansko zrce treće desetice',
  naslov39: 'Četvrta desetica',
  naslov40: '1. Talijansko zrce četvrte desetice',
  naslov41: '2. Talijansko zrce četvrte desetice',
  naslov42: '3. Talijansko zrce četvrte desetice',
  naslov43: '4. Talijansko zrce četvrte desetice',
  naslov44: '5. Talijansko zrce četvrte desetice',
  naslov45: '6. Talijansko zrce četvrte desetice',
  naslov46: '7. Talijansko zrce četvrte desetice',
  naslov47: '8. Talijansko zrce četvrte desetice',
  naslov48: '9. Talijansko zrce četvrte desetice',
  naslov49: '10. Talijansko zrce četvrte desetice',
  naslov50: 'Peta desetica',
  naslov51: '1. Talijansko zrce pete desetice',
  naslov52: '2. Talijansko zrce pete desetice',
  naslov53: '3. Talijansko zrce pete desetice',
  naslov54: '4. Talijansko zrce pete desetice',
  naslov55: '5. Talijansko zrce pete desetice',
  naslov56: '6. Talijansko zrce pete desetice',
  naslov57: '7. Talijansko zrce pete desetice',
  naslov58: '8. Talijansko zrce pete desetice',
  naslov59: '9. Talijansko zrce pete desetice',
  naslov60: '10. Talijansko zrce pete desetice',
  naslov61: 'Završetak krunice',
  prvaDeseticaZalosna: 'Isus, koji se za nas krvlju znojio!',
  prvaDeseticaSlavna: 'Isus, koji je od mrtvih uskrsnuo!',
  prvaDeseticaRadosna: 'Isus, koga si Djevice, po Duhu Svetom začela!',
  prvaDeseticaSvjetla: 'Isus, koji je na rijeci Jordanu kršten bio!',
  drugaDeseticaZalosna: 'Isus, koji je za nas bičevan bio!',
  drugaDeseticaSlavna: 'Isus, koji je na nebo uzašao!',
  drugaDeseticaRadosna: 'Isus, koga si Djevice, Elizabeti u pohode nosila!',
  drugaDeseticaSvjetla: 'Isus, koji nam se na svadbi u Kani objavio!',
  trecaDeseticaZalosna: 'Isus, koji je za nas trnjem okrunjen bio!',
  trecaDeseticaSlavna: 'Isus, koji je Duha Svetog poslao!',
  trecaDeseticaRadosna: 'Isus, koga si Djevice, rodila!',
  trecaDeseticaSvjetla:
    'Isus, koji nam je Kraljevstvo Božje navijestio i na obraćenje pozvao!',
  cetvrtaDeseticaZalosna: 'Isus, koji je za nas teški križ nosio!',
  cetvrtaDeseticaSlavna: 'Isus, koji je Tebe Djevice, na nebo uzeo!',
  cetvrtaDeseticaRadosna: 'Isus, koga si Djevice, u hramu prikazala!',
  cetvrtaDeseticaSvjetla:
    'Isus, koji se na gori preobrazio i svoju nam slavu objavio!',
  petaDeseticaZalosna: 'Isus, koji je za nas raspet bio!',
  petaDeseticaSlavna: 'Isus, koji je Tebe Djevice, na nebu okrunio!',
  petaDeseticaRadosna: 'Isus, koga si Djevice, u hramu našla!',
  petaDeseticaSvjetla: 'Isus, koji nam se u otajstvu euharistije darovao!',
};
